### ISSUE TITLE
Napisy24 Login

### ISSUE THREAD

**Issue by psiriders** [oczkers/psub#2]
Hi,

Despite setting the username/password in psub.yml I get this error:

Traceback (most recent call last):
  File "/usr/local/bin/psub", line 11, in <module>
    load_entry_point('psub==0.0.1', 'console_scripts', 'psub')()
  File "/usr/local/lib/python3.7/site-packages/psub-0.0.1-py3.7.egg/psub/cli.py", line 35, in __main__
  File "/usr/local/lib/python3.7/site-packages/psub-0.0.1-py3.7.egg/psub/core.py", line 58, in download
  File "/usr/local/lib/python3.7/site-packages/psub-0.0.1-py3.7.egg/psub/providers/napisy24.py", line 25, in __init__
  File "/usr/local/lib/python3.7/site-packages/psub-0.0.1-py3.7.egg/psub/providers/napisy24.py", line 55, in login
psub.exceptions.PsubError: Unknown error during login.

**Comment by psiriders** [comment]
Wrong :) I got login/pass switched :) sorry
